version: '3'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - backend

    backend:
        build: ./server
        command: bash -c "/go/bin/app"
        depends_on:
            - postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - backend
            - frontend

    nginx:
        build: ./client
        ports: 
            - "8002:80"
        depends_on:
            - backend
        networks:
            - frontend

networks:
    frontend:
    backend:
