version: '3'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - backend

    golang:
        build: ./server
        depends_on:
            - postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - backend
            - frontend

    nginx:
        build: ./client
        ports: 
            - "80:80"
        depends_on:
            - golang
        networks:
            - frontend

networks:
    frontend:
    backend:
