version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres

    server:
        build: ./server
        command: bash -c "glide update && gin run main.go"
        volumes:
            - ./server/src/app:/go/src/app
        ports:
            - "3000:3000"
        environment:
            - POSTGRES_PASSWORD=postgres
    
