version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres

    server:
        build: ./server
        command: ./main
        depends_on:
            - "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres
    
    nginx:
        build: ./client
        ports: 
            - "8002:80"
